on:
  push:
    branches:
      - "master"
  pull_request:

name: "Linting"

jobs:
  lint:
    name: "Lints"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v3"

      - name: "Install prettier v3.0.3"
        run: |
          yarn global add prettier@3.0.3

      - name: "Install foundry nightly"
        uses: "foundry-rs/foundry-toolchain@v1"
        with:
          version: "nightly"

      - name: "Check prettier format"
        run: |
          prettier --ignore-path .gitignore --check .

      - name: "Check Solidity format"
        run: |
          forge fmt --check
